services:
  - docker
script:
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
  - docker build -t dskyiocom/nginx-alpine-letsencrypt
  - docker push dskyiocom/nginx-alpine-letsencrypt
